# site settings
title: Nam Do
email: namdo1204@gmail.com
description: A Computer Science graduate with professional experience in web development and IT technical support.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Nam Do
city: Tucson
state: AZ
country: United States of America
phone: (520) 265-6455

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/namdo1225
  LinkedIn: https://www.linkedin.com/in/nam-do-630bb2173/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- elements.md
