# This workflow is disabled and no longer needed.

name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helaili/jekyll-action@2.5.0
        build_only: true
